### PR TITLE
Update cryption.go

### PR DESCRIPTION
**Pull request by syed-ghufran-hassan**
- Invalid Key Length: Checks for empty or excessively short keys.
- Data Length Validation: Ensures sufficient data length in encryption/decryption functions.
- HMAC Validation: Returns an error if key or MAC are missing.
- Malformed Payloads: Added validation for improperly formatted payloads.
- Nil Parameters: Public and private keys are validated for nil inputs.
- File Errors: Ensure file existence, readable permissions, and proper formatting when loading keys.

### CODE REVIEW

**Comment by NobleMajo** [comment]
crasy the description and the code look very convincing. thanks so far, i will test it out later.

**Comment by syed-ghufran-hassan** [comment]
Thank you

**Comment by NobleMajo** [comment]
your code looks clean. the tests are running. very good and thank you!

I will make a breakin change based on your change that removes the back channel handling (panic's) and returns the errors.

**Comment by NobleMajo** [comment]
a few notes for the next pull/merge request.
please test your change with ‘make test’ or ‘go test ./...’.
you have removed required functions with your change (project internal and even file internal).

some changes do not make sense. ai generated?

**Comment by syed-ghufran-hassan** [comment]
Hello,

Apology I did not tested properly but from now on I will. Thank you.

Regards,
Ghufran

**Comment by NobleMajo** [comment]
Hii,
still nice to hear from you.
I removed you from the contributer list and reverted your changes.

Please dont use AI code without checking and understanding it.

Regards,
Majo

**Pull request merged**
